### PR TITLE
Restcomm_Python_SDK

### PR DESCRIPTION
**Pull request by mdsharique**

### CODE REVIEW

**Comment by mdsharique** [comment]
Thank you Sir for your reviews and suggestions. I will soon start working on your suggestions.
--i have to see whether we can set namespace to something like "org.restcomm.connect.sdk.python" or not in python. Will implement if possible
--i have already made SDK a package which can be installed with pip. Will share after making required changes

**Comment by gvagenas** [comment]
Great @mdsharique , ping me when ready. 
Thanks

**Comment by mdsharique** [comment]
Respected SIr,

1: I have committed the Project with the required changes which you had
suggested. I have included Test and examples along with it.
2: We cannot set namespace in python. The module acts as a namespace which
is used to import in other files. All the Modules are in a folder named
Restcomm_Python_SDk.
3: I have also uploaded the Project in Pypi. Now We can simply install it
with 'pip install Restcomm_Python_SDk' and use it in our project by 'import
Restcomm_Python_SDk'

Thank you

**Comment by gvagenas** [comment]
@mdsharique , here are my comments:
1. Please merge README.md and README.rst. Why we need the README.rst?
2. Provide more details in the README.md:
- Give a short description of the project (1-2 lines)
- how to build the project
- how to run the tests
- Python version supported
- Reference any dependencies that might be needed to be added by a developer
- Provide instructions for where to download Restcomm and point to the restcomm documentation site
- Provide information how and where developers can open issues and feature requests
3. Is it possible to have difference folder for main classes and test classes. For example for Java we have `main` folder that contians the application classes and `test` that contains the test classes. Is this possible and according to the code style of Python?
4. Provide instructions for the example class you have there, how to run it, what are the prerequisites etc.

In general, imagine a developer familiar with Python but not with Restcomm, that wants to check source code and use it in his project.

We are almost done and after the above minor details we can merge this PR
Please open issues for the missing features/tasks etc and next PRs will be according to those issues.

Great work so far 👍

**Comment by mdsharique** [comment]
@gvagenas As you have asked, I have done all the minor Changes

**Comment by gvagenas** [comment]
Hi @mdsharique great work, I will proceed to the merge now.
Please open issues for the missing features and next tasks and create PR according to the issue you will be working.
Also the tests you provided are not proper and are more examples than unit tests but I will send an email about this, for now we can keep them as is

**Pull request merged**
